# Generated by Django 5.2 on 2025-05-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
