# Generated by Django 5.2 on 2025-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='material',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_of_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_of_product',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('barsyetka', 'Барсетка'), ('bolero', 'Болеро'), ('vetrovka', 'Ветровка'), ('zhiletka', 'Жилетка'), ('kepka', 'Кепка'), ('kovrik_dlya_yogi', 'Коврик для йоги'), ('kostyum', 'Костюм'), ('krossovki', 'Кроссовки'), ('kurtka', 'Куртка'), ('losiny', 'Лосины'), ('mayka', 'Майка'), ('nakolennik', 'Наколенник'), ('napulsnik', 'Напульсник'), ('noski', 'Носки'), ('ochki', 'Очки'), ('perchatki', 'Перчатки'), ('perchatki_dlya_treninga', 'Перчатки для тренинга'), ('platye', 'Платье'), ('polo', 'Поло'), ('ryukzak', 'Рюкзак'), ('sandalii', 'Сандалии'), ('slantsy', 'Сланцы'), ('sumka', 'Сумка'), ('sumka_na_poyas', 'Сумка на пояс'), ('tolstovka', 'Толстовка'), ('top', 'Топ'), ('trusy', 'Трусы'), ('futbolka_base', 'Футболка BASE'), ('futbolka_dl_rukav', 'Футболка дл рукав'), ('futbolka', 'Футболка'), ('shapka', 'Шапка'), ('shorty', 'Шорты'), ('shorty_base', 'Шорты BASE'), ('shtany', 'Штаны'), ('shtany_base', 'Штаны BASE')], default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
