# Generated by Django 5.2 on 2025-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('demix', 'Demix'), ('emporio armani', 'Emporio Armani'), ('hugo boss', 'Hugo Boss'), ('jack wolfskin', 'Jack Wolfskin'), ('joss', 'Joss'), ('kelme', 'Kelme'), ('molten', 'Molten'), ('nike', 'Nike'), ('puma', 'Puma'), ('outventure', 'Outventure'), ('speedo', 'Speedo'), ('ander armour', 'Under Armour')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='material',
            field=models.CharField(blank=True, choices=[('cotton', 'Пахта'), ('wool', 'Жүн'), ('silk', 'Жибек'), ('linen', 'Лён'), ('bamboo', 'Бамбук'), ('polyester', 'Полиэстер'), ('nylon', 'Нейлон'), ('acrylic', 'Акрил'), ('spandex', 'Эластан'), ('microfiber', 'Микрофибра'), ('cotton_polyester', 'Пахта + Полиэстер'), ('wool_acrylic', 'Жүн + Акрил'), ('silk_nylon', 'Жибек + Нейлон')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('demix', 'Demix'), ('emporio armani', 'Emporio Armani'), ('hugo boss', 'Hugo Boss'), ('jack wolfskin', 'Jack Wolfskin'), ('joss', 'Joss'), ('kelme', 'Kelme'), ('molten', 'Molten'), ('nike', 'Nike'), ('puma', 'Puma'), ('outventure', 'Outventure'), ('speedo', 'Speedo'), ('ander armour', 'Under Armour')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('бирюзовый', 'Бирюзовый'), ('бордовый', 'Бордовый'), ('голубой', 'Голубой'), ('желто-зеленый', 'Желто-зеленый'), ('желтый', 'Желтый'), ('зеленый', 'Зеленый'), ('коричневый', 'Коричневый'), ('красный', 'Красный'), ('оливковый', 'Оливковый'), ('персиковый', 'Персиковый'), ('розовый', 'Розовый'), ('светло-серый', 'Светло-серый'), ('светло-синий', 'Светло-синий'), ('серый', 'Серый'), ('синий', 'Синий'), ('сиреневый', 'Сиреневый'), ('фиолетовый', 'Фиолетовый'), ('черный', 'Черный')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('cotton', 'Пахта'), ('wool', 'Жүн'), ('silk', 'Жибек'), ('linen', 'Лён'), ('bamboo', 'Бамбук'), ('polyester', 'Полиэстер'), ('nylon', 'Нейлон'), ('acrylic', 'Акрил'), ('spandex', 'Эластан'), ('microfiber', 'Микрофибра'), ('cotton_polyester', 'Пахта + Полиэстер'), ('wool_acrylic', 'Жүн + Акрил'), ('silk_nylon', 'Жибек + Нейлон')], max_length=100, null=True),
        ),
    ]
