# Generated by Django 5.2 on 2025-05-03 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_name_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('demix', 'Demix'), ('emporio armani', 'Emporio Armani'), ('hugo boss', 'Hugo Boss'), ('jack wolfskin', 'Jack Wolfskin'), ('joss', 'Joss'), ('kelme', 'Kelme'), ('molten', 'Molten'), ('nike', 'Nike'), ('puma', 'Puma'), ('outventure', 'Outventure'), ('speedo', 'Speedo'), ('under armour', 'Under Armour')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('demix', 'Demix'), ('emporio armani', 'Emporio Armani'), ('hugo boss', 'Hugo Boss'), ('jack wolfskin', 'Jack Wolfskin'), ('joss', 'Joss'), ('kelme', 'Kelme'), ('molten', 'Molten'), ('nike', 'Nike'), ('puma', 'Puma'), ('outventure', 'Outventure'), ('speedo', 'Speedo'), ('under armour', 'Under Armour')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('2XS', '2XS'), ('2XL', '2XL'), ('LXL', 'LXL'), ('SM', 'SM'), ('ML', 'ML'), ('128', '128'), ('140', '140'), ('152', '152'), ('164', '164'), ('30', '30'), ('32', '32'), ('34', '34'), ('34 - 38', '34 - 38'), ('35.5', '35.5'), ('36', '36'), ('36.5', '36.5'), ('37', '37'), ('37.5', '37.5'), ('38', '38'), ('38.5', '38.5'), ('39', '39'), ('40', '40'), ('40.5', '40.5'), ('41', '41'), ('42', '42'), ('42.5', '42.5'), ('43', '43'), ('44', '44'), ('44.5', '44.5'), ('45', '45'), ('45.5', '45.5'), ('46', '46'), ('46.5', '46.5'), ('47', '47'), ('47.5', '47.5'), ('48', '48'), ('48.5', '48.5'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('62', '62'), ('66', '66'), ('ADULT', 'ADULT'), ('One', 'One Size'), ('38 - 42', '38 - 42'), ('39 - 42', '39 - 42'), ('41 - 43', '41 - 43'), ('42 - 46', '42 - 46'), ('43 - 46', '43 - 46'), ('44 - 45.5', '44 - 45.5'), ('46 - 48', '46 - 48'), ('46 - 50', '46 - 50')], max_length=20),
        ),
    ]
