# Generated by Django 5.2 on 2025-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='type_of_product',
            field=models.CharField(choices=[('barsyetka', 'Барсетка'), ('berushi', 'Беруши'), ('bolero', 'Болеро'), ('butylka', 'Бутылка'), ('vetrovka', 'Ветровка'), ('zhiletka', 'Жилетка'), ('kepka', 'Кепка'), ('kovrik_dlya_yogi', 'Коврик для йоги'), ('kostyum', 'Костюм'), ('krossovki', 'Кроссовки'), ('kurtka', 'Куртка'), ('losiny', 'Лосины'), ('mayka', 'Майка'), ('myach', 'Мяч'), ('nakolennik', 'Наколенник'), ('napulsnik', 'Напульсник'), ('noski', 'Носки'), ('ochki', 'Очки'), ('perchatki', 'Перчатки'), ('perchatki_dlya_treninga', 'Перчатки для тренинга'), ('platye', 'Платье'), ('polo', 'Поло'), ('ryukzak', 'Рюкзак'), ('sandalii', 'Сандалии'), ('slantsy', 'Сланцы'), ('sumka', 'Сумка'), ('sumka_na_poyas', 'Сумка на пояс'), ('tolstovka', 'Толстовка'), ('top', 'Топ'), ('trusy', 'Трусы'), ('futbolka_base', 'Футболка BASE'), ('futbolka_dl_rukav', 'Футболка дл рукав'), ('futbolka', 'Футболка.'), ('shapka', 'Шапка'), ('shorty', 'Шорты'), ('shorty_base', 'Шорты BASE'), ('shtany', 'Штаны'), ('shtany_base', 'Штаны BASE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('barsyetka', 'Барсетка'), ('berushi', 'Беруши'), ('bolero', 'Болеро'), ('butylka', 'Бутылка'), ('vetrovka', 'Ветровка'), ('zhiletka', 'Жилетка'), ('kepka', 'Кепка'), ('kovrik_dlya_yogi', 'Коврик для йоги'), ('kostyum', 'Костюм'), ('krossovki', 'Кроссовки'), ('kurtka', 'Куртка'), ('losiny', 'Лосины'), ('mayka', 'Майка'), ('myach', 'Мяч'), ('nakolennik', 'Наколенник'), ('napulsnik', 'Напульсник'), ('noski', 'Носки'), ('ochki', 'Очки'), ('perchatki', 'Перчатки'), ('perchatki_dlya_treninga', 'Перчатки для тренинга'), ('platye', 'Платье'), ('polo', 'Поло'), ('ryukzak', 'Рюкзак'), ('sandalii', 'Сандалии'), ('slantsy', 'Сланцы'), ('sumka', 'Сумка'), ('sumka_na_poyas', 'Сумка на пояс'), ('tolstovka', 'Толстовка'), ('top', 'Топ'), ('trusy', 'Трусы'), ('futbolka_base', 'Футболка BASE'), ('futbolka_dl_rukav', 'Футболка дл рукав'), ('futbolka', 'Футболка.'), ('shapka', 'Шапка'), ('shorty', 'Шорты'), ('shorty_base', 'Шорты BASE'), ('shtany', 'Штаны'), ('shtany_base', 'Штаны BASE')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
