# Generated by Django 5.2 on 2025-05-18 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_slug_alter_product_size_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('demix', 'Demix'), ('emporio armani', 'Emporio Armani'), ('hugo boss', 'Hugo Boss'), ('jack wolfskin', 'Jack Wolfskin'), ('joss', 'Joss'), ('kelme', 'Kelme'), ('molten', 'Molten'), ('nike', 'Nike'), ('puma', 'Puma'), ('outventure', 'Outventure'), ('speedo', 'Speedo'), ('under armour', 'Under Armour')], default='nike', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='material',
            field=models.CharField(blank=True, choices=[('cotton', 'Пахта'), ('wool', 'Жүн'), ('silk', 'Жибек'), ('linen', 'Лён'), ('bamboo', 'Бамбук'), ('polyester', 'Полиэстер'), ('nylon', 'Нейлон'), ('acrylic', 'Акрил'), ('spandex', 'Эластан'), ('microfiber', 'Микрофибра'), ('cotton_polyester', 'Пахта + Полиэстер'), ('wool_acrylic', 'Жүн + Акрил'), ('silk_nylon', 'Жибек + Нейлон')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type_of_product',
            field=models.CharField(choices=[('barsyetka', 'Барсетка'), ('bolero', 'Болеро'), ('vetrovka', 'Ветровка'), ('zhiletka', 'Жилетка'), ('kepka', 'Кепка'), ('kovrik_dlya_yogi', 'Коврик для йоги'), ('kostyum', 'Костюм'), ('krossovki', 'Кроссовки'), ('kurtka', 'Куртка'), ('losiny', 'Лосины'), ('mayka', 'Майка'), ('nakolennik', 'Наколенник'), ('napulsnik', 'Напульсник'), ('noski', 'Носки'), ('ochki', 'Очки'), ('perchatki', 'Перчатки'), ('perchatki_dlya_treninga', 'Перчатки для тренинга'), ('platye', 'Платье'), ('polo', 'Поло'), ('ryukzak', 'Рюкзак'), ('sandalii', 'Сандалии'), ('slantsy', 'Сланцы'), ('sumka', 'Сумка'), ('sumka_na_poyas', 'Сумка на пояс'), ('tolstovka', 'Толстовка'), ('top', 'Топ'), ('trusy', 'Трусы'), ('futbolka_base', 'Футболка BASE'), ('futbolka_dl_rukav', 'Футболка дл рукав'), ('futbolka', 'Футболка.'), ('shapka', 'Шапка'), ('shorty', 'Шорты'), ('shorty_base', 'Шорты BASE'), ('shtany', 'Штаны'), ('shtany_base', 'Штаны BASE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('barsyetka', 'Барсетка'), ('bolero', 'Болеро'), ('vetrovka', 'Ветровка'), ('zhiletka', 'Жилетка'), ('kepka', 'Кепка'), ('kovrik_dlya_yogi', 'Коврик для йоги'), ('kostyum', 'Костюм'), ('krossovki', 'Кроссовки'), ('kurtka', 'Куртка'), ('losiny', 'Лосины'), ('mayka', 'Майка'), ('nakolennik', 'Наколенник'), ('napulsnik', 'Напульсник'), ('noski', 'Носки'), ('ochki', 'Очки'), ('perchatki', 'Перчатки'), ('perchatki_dlya_treninga', 'Перчатки для тренинга'), ('platye', 'Платье'), ('polo', 'Поло'), ('ryukzak', 'Рюкзак'), ('sandalii', 'Сандалии'), ('slantsy', 'Сланцы'), ('sumka', 'Сумка'), ('sumka_na_poyas', 'Сумка на пояс'), ('tolstovka', 'Толстовка'), ('top', 'Топ'), ('trusy', 'Трусы'), ('futbolka_base', 'Футболка BASE'), ('futbolka_dl_rukav', 'Футболка дл рукав'), ('futbolka', 'Футболка.'), ('shapka', 'Шапка'), ('shorty', 'Шорты'), ('shorty_base', 'Шорты BASE'), ('shtany', 'Штаны'), ('shtany_base', 'Штаны BASE')], default='nike', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
