# Generated by Django 5.2 on 2025-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0002_category_brand_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('demix', 'Demix'), ('emporio armani', 'Emporio Armani'), ('hugo boss', 'Hugo Boss'), ('jack wolfskin', 'Jack Wolfskin'), ('joss', 'Joss'), ('kelme', 'Kelme'), ('molten', 'Molten'), ('nike', 'Nike'), ('puma', 'Puma'), ('outventure', 'Outventure'), ('speedo', 'Speedo'), ('under armour', 'Under Armour')], default='default_brand', max_length=100),
        ),
    ]
